#!/usr/bin/env bash

path="/root/oai-deployment-files"

kubectl delete -f "${path}/oai-enb-devel.yaml"
kubectl delete  -f "${path}/oai-spgwc-devel.yaml"
kubectl delete -f "${path}/oai-spgwu-devel.yaml"
kubectl delete  -f "${path}/oai-mme-devel.yaml" 
kubectl delete -f "${path}/oai-hss-devel.yaml" 
kubectl delete -f "${path}/cassandra.yaml" 
