hss_hostname: oai-hss
hss_ip: oai-hss.oai.svc.cluster.local
hss_realm: oai.svc.cluster.local
hss_service: oai-hss.oai.svc.cluster.local
mcc: "208"
mme_cidr_s10: 127.0.0.1/32
mme_cidr_s11: 172.16.1.100/24
mme_cidr_s1c: 192.168.1.100/24
mme_code: "1"
mme_gid: "4"
mme_realm: oai.svc.cluster.local
mme_service: oai-mme.oai.svc.cluster.local
mnc: "93"
nw_if_s10: lo
nw_if_s11: net2
nw_if_s1c: net1
sgw_cidr_s11: 172.16.1.101/24
tac: "1"
