apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: oai
spec:
  selector:
    matchLabels:
      run: core
  replicas: 1
  template:
    metadata:
      name: core
      annotations:
        k8s.v1.cni.cncf.io/networks: core-net1, core-net2
      labels:
        app: core
        run: core
    spec:
      containers:
        - name: core
          image: ttsourdinis/nextepc
          securityContext:
              privileged: true
          command: ["/bin/sh", "-c"]
          args:
          - sudo ip tuntap add name pgwtun mode tun;
            sudo ip addr add 172.16.0.1/24 dev pgwtun;
            sudo ip link set pgwtun up;
            sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward";
            mongod&
            sleep 2;
            ./nextepc/nextepc-epcd&
            while true;
            do sleep 30;
            done;
---
apiVersion: v1
kind: Service
metadata:
  name: core-svc
  namespace: oai
spec:
  type: NodePort
  selector:
    app: core
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: core-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.1.100/24",
    "gateway": "192.168.1.1" } ] } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: core-net2
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "172.16.2.100/24",
    "gateway": "172.16.2.1" } ] } }'
