apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: enb-net3
  namespace: oai
spec:
 config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth1", "mode": "bridge", "ipam": { "type": "host-local", "subnet": "192.168.18.0/24", "rangeStart": "192.168.18.1", "rangeEnd": "192.168.18.200", "gateway": "192.168.18.1" } }'
