apiVersion: v1
kind: ServiceAccount
metadata:
  name: oaicn-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oaicn-rbac
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: oaicn-sa
  namespace: oai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-cn
  name: oai-cn
  namespace: oai
spec:
  clusterIP: None
  ports:
<<<<<<< HEAD
  - name: oai-cn
    port: 22100
    protocol: TCP
    targetPort: 22100
  - name: s1u
    port: 2152
    protocol: UDP
    targetPort: 2152
  - name: s1c
    port: 36412
    protocol: UDP
    targetPort: 36412
  - name: x2c
    port: 36422
    protocol: UDP
    targetPort: 36422
  - name: if5-ori
    port: 50000
    protocol: UDP
    targetPort: 50000
  - name: if5-ecpri
    port: 50001
    protocol: UDP
    targetPort: 50001
=======
  - name: oai-hss
    port: 3868
    protocol: TCP
    targetPort: 3868
  - name: oai-hss-secure
    port: 5868
    protocol: TCP
    targetPort: 5868  
  - name: oai-mme
    port: 3870
    protocol: TCP
    targetPort: 3870
  - name: oai-mme-secure
    port: 5870
    protocol: TCP
    targetPort: 5870
  - name: s11
    port: 2123
    protocol: TCP
    targetPort: 2123
>>>>>>> ecd14726696ac6f34bd2dd022e44f1ae9417b3e3
  selector:
    app: oai-cn
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-cn
  labels:
    app: oai-cn
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-cn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
<<<<<<< HEAD
        k8s.v1.cni.cncf.io/networks: oaicn-net1
=======
        k8s.v1.cni.cncf.io/networks: cn-net1,cn-net2
>>>>>>> ecd14726696ac6f34bd2dd022e44f1ae9417b3e3
      labels:
        app: oai-cn
    spec:
      containers:
      - name: oai-cn
        image: 194.177.207.79:5000/oai/oai-rru-devel
        command:
          - "sleep"
          - "604800"
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        ports:
<<<<<<< HEAD
        - containerPort: 22100
          name: oai-cn
        - containerPort: 2152
          name: s1u
        - containerPort: 36412
          name: s1c
        - containerPort: 36422
          name: x2c
        - containerPort: 50000
          name: if5-ori
        - containerPort: 50001
          name: if5-ecpri
=======
        - containerPort: 3868
          name: oai-hss
        - containerPort: 5868
          name: oai-hss-secure
        - containerPort: 9080
          name: jmx
        - containerPort: 9081
          name: cql
        - containerPort: 3870
          name: oai-mme
        - containerPort: 5870
          name: oai-mme-secure
        - containerPort: 2123
          name: s11 
>>>>>>> ecd14726696ac6f34bd2dd022e44f1ae9417b3e3
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        type: rru
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: oaicn-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
<<<<<<< HEAD
  name: oaicn-net3
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth1", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.204/24",
    "gateway": "192.168.18.1" } ] } }'
=======
  name: cn-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.1.100/24",
    "gateway": "192.168.1.1" } ] } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cn-net2
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "172.16.1.100/24",
    "gateway": "172.16.1.1" } ] } }'
>>>>>>> ecd14726696ac6f34bd2dd022e44f1ae9417b3e3
