apiVersion: v1
kind: ServiceAccount
metadata:
  name: rru-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rru-rbac
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rru-sa
  namespace: oai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-rru
  name: oai-rru
  namespace: oai
spec:
  clusterIP: None
  ports:
  - name: oai-rru
    port: 50000
    targetPort: 50000
  - name: oai-rru1
    port: 50001
    targetPort: 50001
  - name: oai-rru2
    port: 50010
    targetPort: 50010
  - name: oai-rru3
    port: 50011
    targetPort: 50011
  selector:
    app: oai-rru
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-rru
  labels:
    app: oai-rru
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-rru
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rru-net3
      labels:
        app: oai-rru
    spec:
      initContainers:
      - name: kubeconfig
        automountServiceAccountToken: true
        image: gcr.io/cloud-builders/kubectl:latest
        command: ["sh", "-c"]
        args:
          - echo starting init container;
            kubectl delete network-attachment-definitions enb-net3 -n oai;
            $(eval "cat <<EOF | kubectl apply -f -
            apiVersion: 'k8s.cni.cncf.io/v1'
            kind: NetworkAttachmentDefinition
            metadata:
              name: enb-net3
            spec:
              config: '{
                  "cniVersion": "0.3.0",
                  "type": "macvlan",
                  "master": "eth1",
                  "mode": "bridge",
                  "ipam": {
                    "type": "host-local",
                    "subnet": "192.168.1.0/24",
                    "rangeStart": "192.168.18.7",
                    "rangeEnd": "192.168.18.254",
                             "gateway": "192.168.18.1"
                   }
                  }'
            EOF");
            echo done;
      containers:
      - name: oai-rru
        image: 194.177.207.79:5000/oai/oai5g_enb
        command:
          - "sleep"
          - "604800"
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        ports:
        - containerPort: 50000
          name: oai-rru
        - containerPort: 50001
          name: oai-rru1
        - containerPort: 50010
          name: oai-rru2
        - containerPort: 50011
          name: oai-rru3
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/bus/usb
          name: ttyusb
      volumes:
      - name: ttyusb
        hostPath:
          path: /dev/bus/usb
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        type: rru
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: rru-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rru-net3
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth1", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.205/24",
    "gateway": "192.168.18.1" } ] } }'
