apiVersion: v1
kind: ServiceAccount
metadata:
  name: ue-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ue-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ue-sa
  namespace: oai
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-config
  namespace: oai
data:
  band: "38"
  ru_local_if: "net1"
  ru_local_ip: "192.168.18.199"
  ru_remote_ip: "192.168.18.206"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-ue
  name: oai-ue
  namespace: oai
spec:
  clusterIP: None
  ports:
  - name: if4p5-c
    port: 50000
    protocol: UDP
    targetPort: 50000
  - name: if4p5-u
    port: 50001
    protocol: UDP
    targetPort: 50001
  selector:
    app: oai-ue
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oai-ue
  name: oai-ue
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-ue
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: ue-net1
      labels:
        app: oai-ue
    spec:
      containers:
      - env:
        - name: RU_LOCAL_IF
          valueFrom:
            configMapKeyRef:
              key: ru_local_if
              name: ue-config
        - name: RU_LOCAL_IP
          valueFrom:
            configMapKeyRef:
              key: ru_local_ip
              name: ue-config
        - name: RU_REMOTE_IP
          valueFrom:
            configMapKeyRef:
              key: ru_remote_ip
              name: ue-config
        - name: BAND
          valueFrom:
            configMapKeyRef:
              key: band
              name: ue-config
        image: 10.0.1.8:5000/oai/oai-ue-devel
        imagePullPolicy: Always
        name: ue
        ports:
        - containerPort: 50000
          name: if4p5-c
        - containerPort: 50001
          name: if4p5-u
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: regcred
      - command:
        - /bin/sleep
        - infinity
        image: corfr/tcpdump
        name: tcpdump
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: ue-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ue-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.199/24",
    "gateway": "192.168.18.1" } ] } }'
