apiVersion: v1
kind: ServiceAccount
metadata:
  name: rru-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rru-rbac
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rru-sa
  namespace: oai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-rcc
  name: oai-rcc
  namespace: oai
spec:
  clusterIP: None
  ports:
  - name: oai-rcc
    port: 22100
    protocol: TCP
    targetPort: 22100
  - name: s1u
    port: 2152
    protocol: UDP
    targetPort: 2152
  - name: s1c
    port: 36412
    protocol: UDP
    targetPort: 36412
  - name: x2c
    port: 36422
    protocol: UDP
    targetPort: 36422
  - name: if5-ori
    port: 50000
    protocol: UDP
    targetPort: 50000
  - name: if5-ecpri
    port: 50001
    protocol: UDP
    targetPort: 50001
  selector:
    app: oai-rcc
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-rcc
  labels:
    app: oai-rcc
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-rcc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: rcc-net1,rcc-net2,rcc-net3
      labels:
        app: oai-rcc
    spec:
      containers:
      - name: oai-rcc
        image: 194.177.207.79:5000/oai/oai-rcc-exper
        command:
          - "sleep"
          - "604800"
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        ports:
        - containerPort: 22100
          name: oai-rcc
        - containerPort: 2152
          name: s1u
        - containerPort: 36412
          name: s1c
        - containerPort: 36422
          name: x2c
        - containerPort: 50000
          name: if5-ori
        - containerPort: 50001
          name: if5-ecpri
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        type: rru
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: rru-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rcc-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "192.168.1.101/24",
    "gateway": "192.168.1.1" } ] } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rcc-net2
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "ipam": { "type": "static", "addresses": [ { "address": "172.16.2.101/24",
    "gateway": "172.16.2.1" } ] } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: rcc-net3
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "eth1", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.206/24",
    "gateway": "192.168.18.1" } ] } }'
