enb_id: "00e00"
enb_name: "eNB-Eurecom-LTEBox"
mcc: "208"
mme_ip4: "192.168.1.100"
mme_ip6: "::1"
mnc: "93"
mnc_length: "2"
ru_local_if: "net3"
ru_local_ip: "oai-rru"
ru_remote_ip: "oai-enb"
s1_mme_if: "net1"
s1_mme_ip: "oai-mme"
s1_u_if: "net2"
s1_u_ip: "172.16.2.101"
tac: "1"
x2c_ip: "172.16.2.101"
