apiVersion: v1
kind: Service
metadata:
  labels:
    app: onos
  name: onos
  namespace: oai
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
      nodePort: 30006
    - name: "8101"
      port: 8101
      targetPort: 8101
      nodePort: 30007
  selector:
    app: onos
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onos
  name: onos
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos
  strategy:
    type: Recreate       
  template:
    metadata:
      annotations:
      labels:
        app: onos
    spec:
      containers:
        - env:
            - name: ONOS_APPS
              value: gui2,drivers.bmv2,lldpprovider,netcfghostprovider
          image: karamiha/onos:2.2.2-ssh
          name: onos
          #command:
          #  - "sleep"
          #  - "604800"
          resources:
            requests:
              cpu: 2
              memory: 4Gi
          ports:
            - containerPort: 8181
            - containerPort: 8101
      hostname: onos
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
