apiVersion: v1
kind: ServiceAccount
metadata:
  name: sctp-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sctp-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: sctp-sa
  namespace: oai
---
apiVersion: v1
data:
  entrypoint.sh: |
    #!/bin/bash
    set -eo pipefail
    echo "###################################"
    echo "Script to enable sctp kernel module"
    echo "###################################"
    /sbin/modprobe sctp
    if [ $(lsmod | grep sctp | wc -l) -eq 0 ]
    then
      echo "SCTP module not loaded"
      exit 1
    else
      echo "SCTP module successfully loaded"
      while true; do sleep 10; done
    fi
kind: ConfigMap
metadata:
  name: sctp-entrypoint
  namespace: oai
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sctp-ds
  name: sctp-ds
  namespace: oai
spec:
  selector:
    matchLabels:
      app: sctp-ds
  template:
    metadata:
      labels:
        app: sctp-ds
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - command:
        - sh
        - -c
        - source /root/entrypoint.sh
        image: 10.0.1.8:5000/ubi8/ubi-minimal
        name: sctp-loader
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /root
          name: sctp-script
        - mountPath: /bin
          name: binaries
        - mountPath: /sbin
          name: sbinaries
        - mountPath: /lib/modules
          name: modules
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: sctp-sa
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: sctp-entrypoint
        name: sctp-script
      - hostPath:
          path: /bin/
          type: Directory
        name: binaries
      - hostPath:
          path: /sbin/
          type: Directory
        name: sbinaries
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
